import app from 'flarum/app';

app.initializers.add('therealsujitk-hljs', (app) => {
    const themes = {
        'default': 'Default',
        'a11y-dark': "A 11 Y Dark",
        'a11y-light': 'A 11 Y Light',
        'agate': 'Agate',
        'an-old-hope': 'An Old Hope',
        'androidstudio': 'Androidstudio',
        'arduino-light': 'Arduino Light',
        'arta': 'Arta',
        'ascetic': 'Ascetic',
        'atelier-cave-dark': 'Atelier Cave Dark',
        'atelier-cave-light': 'Atelier Cave Light',
        'atelier-dune-dark': 'Atelier Dune Dark',
        'atelier-dune-light': 'AAtelier Dune Light',
        'atelier-estuary-dark': 'Atelier Estuary Dark',
        'atelier-estuary-light': 'Atelier Estuary Light',
        'atelier-forest-dark': 'Atelier Forest Dark',
        'atelier-forest-light': 'Atelier Forest Light',
        'atelier-heath-dark': 'Atelier Heath Dark',
        'atelier-heath-light': 'Atelier Heath Light',
        'atelier-lakeside-dark': 'Atelier Lakeside Dark',
        'atelier-lakeside-light': 'Atelier Lakeside Light',
        'atelier-plateau-dark': 'Atelier Plateau Dark',
        'atelier-plateau-light': 'Atelier Plateau Light',
        'atelier-savanna-dark': 'Atelier Savanna Dark',
        'atelier-savanna-light': 'Atelier Savanna Light',
        'atelier-seaside-dark': 'Atelier Seaside Dark',
        'atelier-seaside-light': 'Atelier Seaside Light',
        'atelier-sulphurpool-dark': 'Atelier Sulphurpool Dark',
        'atelier-sulphurpool-light': 'Atelier Sulphurpool Light',
        'atom-one-dark-reasonable': 'Atom One Dark Reasonable',
        'atom-one-dark': 'Atom One Dark',
        'atom-one-light': 'Atom One Light',
        'brown-paper': 'Brown Paper',
        'codepen-embed': 'Codepen Embed',
        'color-brewer': 'Color Brewer',
        'darcula': 'Darcula',
        'dark': 'Dark',
        'docco': 'Docco',
        'dracula': 'Dracula',
        'far': 'Far',
        'foundation': 'Foundation',
        'github-gist': 'GitHub  Gist',
        'github': 'GitHub',
        'gml': 'Gml',
        'googlecode': 'Googlecode',
        'gradient-dark': 'Gradient Dark',
        'gradient-light': 'Gradient Light',
        'grayscale': 'Grayscale',
        'gruvbox-dark': 'Gruvbox Dark',
        'gruvbox-light': 'Gruvbox Light',
        'hopscotch': 'Hopscotch',
        'hybrid': 'Hybrid',
        'idea': 'Idea',
        'ir-black': 'Ir Black',
        'isbl-editor-dark': 'Isbl Editor Dark',
        'isbl-editor-light': 'Isbl Editor Light',
        'kimbie.dark': 'Kimbie Dark',
        'kimbie.light': 'Kimbie Light',
        'lightfair': 'Lightfair',
        'lioshi': 'Lioshi',
        'magula': 'Magula',
        'mono-blue': 'Mono Blue',
        'monokai-sublime': 'Monokai Sublime',
        'monokai': 'Monokai',
        'night-owl': 'Night Owl',
        'hopscotch': 'hopscotch',
        'nnfx-dark': 'Nnfx Dark',
        'nnfx': 'Nnfx',
        'nord': 'Nord',
        'obsidian': 'Obsidian',
        'ocean': 'Ocean',
        'paraiso-dark': 'Paraiso Dark',
        'paraiso-light': 'Paraiso Light',
        'pojoaque': 'Pojoaque',
        'purebasic': 'Purebasic',
        'qtcreator-dark': 'Qtcreator Dark',
        'qtcreator-light': 'Qtcreator Light',
        'railscasts': 'Railscasts',
        'rainbow': 'Rainbow',
        'routeros': 'Routeros',
        'school-book': 'School Book',
        'shades-of-purple': 'Shades Of Purple',
        'solarized-dark': 'Solarized Dark',
        'solarized-light': 'Solarized Light',
        'srcery': 'Srcery',
        'stackoverflow-dark': 'Stackoverflow Dark',
        'stackoverflow-light': 'Stackoverflow Light',
        'sunburst': 'Sunburst',
        'tomorrow-night-blue': 'Tomorrow Night Blue',
        'tomorrow-night-bright': 'Tomorrow Night Bright',
        'tomorrow-night-eighties': 'Tomorrow Night Eighties',
        'tomorrow-night': 'Tomorrow Night',
        'tomorrow': 'Tomorrow',	
        'vs': 'Vs',
        'vs2015': 'Vs 2015',
        'xcode': 'Xcode',
        'xt256': 'Xt 256',
        'zenburn': 'Zenburn'
    };

    app.extensionData.for('therealsujitk-hljs')
        .registerSetting({
            setting: 'therealsujitk-hljs.theme_name',
            type: 'select',
            options: themes,
            default: 'default',
            label: app.translator.trans('therealsujitk.admin.hljs.themename')
        })
});